name: color-match
version: 1.0.2
summary: Color Match
description: Very hard game with no rewards.
confinement: strict
base: core18
apps:
  color-match:
    command: color_match
    extensions: [flutter-master]
parts:
  color-match:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # app's main entry-point file
